<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/11/03 12:06:26
$this->security = array (
  'addtag' => 
  array (
    'is_secure' => true,
  ),
  'removetag' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
