<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/11/03 12:06:26
sfConfig::add(array(
  'mod_taggablecomplete_enabled' => true,
  'mod_taggablecomplete_view_class' => 'sfPHP',
));
