<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/11/03 08:03:17
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'superadmin',
        1 => 'admin',
      ),
    ),
  ),
);
