<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/11/02 15:21:51
sfConfig::add(array(
  'mod_aslideshowslot_enabled' => true,
  'mod_aslideshowslot_view_class' => 'sfPHP',
));
